# config.yml
local_backend: true

backend:
  name: git-gateway
  repo: th-koeln/mi-website-2018
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/uploads'

collections:
  - name: 'event'
    label: 'Event'
    hint: 'Hier kommen Events rein.'
    folder: 'content/events'
    create: true
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    editor:
      preview: true
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Link Titel', name: 'linkTitle', widget: 'string' }
      - { label: 'Termin (der angezeigt werden soll)', name: 'termin', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Date (zur Sortierung)", name: "datum", widget: "datetime", default: "", date_format: "YYYY-MM-DDTHH:mm:ss" }
      - label: "Featured Image"
        name: "image"
        widget: "image"
        choose_url: true
        media_library:
          config:
            slug: "teaser-{{filename}}"
            max_file_size: 512000 # in bytes, only for default media library
  
  - name: 'snaps'
    label: 'Eindrücke'
    hint: 'Hier kommen Bilder und Filmchen rein, die wir dann auf der Seite verteilen.'
    folder: 'content/snaps'
    create: true
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    editor:
      preview: true
    fields:
      - { label: 'Caption', name: 'title', widget: 'string' }
      - { label: 'Autor', name: 'Autor', widget: 'string' }
      - { label: "Date (zur Sortierung)", name: "datum", widget: "datetime", default: "", date_format: "YYYY-MM-DDTHH:mm:ss" }
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
        allow_multiple: true
        media_library:
          config:
            slug: "{{filename}}"
            max_file_size: 512000 # in bytes, only for default media library
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["Bachelor", "Master", "Event", "Teaching", "Atmo", "Working"]
        default: ["Atmo"]

